/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const BuyerTier = IDL.Variant({
  'tier1' : IDL.Null,
  'tier2' : IDL.Null,
  'tier3' : IDL.Null,
  'tier4' : IDL.Null,
});
export const SupplierSize = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const FeedbackStatus = IDL.Variant({
  'new' : IDL.Null,
  'closed' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'status' : FeedbackStatus,
  'userType' : IDL.Text,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
});
export const RFQStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
  'quoted' : IDL.Null,
});
export const RFQ = IDL.Record({
  'id' : IDL.Nat,
  'status' : RFQStatus,
  'createdAt' : Timestamp,
  'productId' : IDL.Nat,
  'requiredDate' : IDL.Text,
  'quoteAmount' : IDL.Opt(IDL.Float64),
  'buyerId' : UserId,
  'quantity' : IDL.Nat,
  'specialRequirements' : IDL.Text,
  'supplierId' : UserId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'supplier' : IDL.Null,
  'both' : IDL.Null,
  'buyer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'verified' : IDL.Bool,
  'supplierSize' : IDL.Opt(SupplierSize),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : IDL.Text,
  'buyerTier' : IDL.Opt(BuyerTier),
});
export const ProductStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'status' : ProductStatus,
  'specifications' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'certifications' : IDL.Text,
  'price' : IDL.Float64,
  'supplierId' : UserId,
});
export const Result_2 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [Result_1],
      [],
    ),
  'calculateBuyerFee' : IDL.Func(
      [BuyerTier, IDL.Float64],
      [IDL.Float64],
      ['query'],
    ),
  'calculateMultiRoleFee' : IDL.Func(
      [BuyerTier, SupplierSize, IDL.Float64, IDL.Float64],
      [IDL.Float64],
      ['query'],
    ),
  'calculateSupplierFee' : IDL.Func(
      [SupplierSize, IDL.Float64],
      [IDL.Float64],
      ['query'],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [Result], []),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllRFQs' : IDL.Func([], [IDL.Vec(RFQ)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getIncomingRFQs' : IDL.Func([], [IDL.Vec(RFQ)], ['query']),
  'getMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyRFQs' : IDL.Func([], [IDL.Vec(RFQ)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, UserRole, IDL.Opt(BuyerTier), IDL.Opt(SupplierSize)],
      [Result_2],
      [],
    ),
  'respondToRFQ' : IDL.Func([IDL.Nat, IDL.Float64], [Result], []),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result_1], []),
  'submitRFQ' : IDL.Func(
      [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [Result_1],
      [],
    ),
  'updateFeedbackStatus' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Nat, IDL.Text],
      [Result],
      [],
    ),
  'updateRFQStatus' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
  'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [Result], []),
  'verifyUser' : IDL.Func([IDL.Principal], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result_1 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const BuyerTier = IDL.Variant({
    'tier1' : IDL.Null,
    'tier2' : IDL.Null,
    'tier3' : IDL.Null,
    'tier4' : IDL.Null,
  });
  const SupplierSize = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const FeedbackStatus = IDL.Variant({
    'new' : IDL.Null,
    'closed' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'status' : FeedbackStatus,
    'userType' : IDL.Text,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const RFQStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
    'quoted' : IDL.Null,
  });
  const RFQ = IDL.Record({
    'id' : IDL.Nat,
    'status' : RFQStatus,
    'createdAt' : Timestamp,
    'productId' : IDL.Nat,
    'requiredDate' : IDL.Text,
    'quoteAmount' : IDL.Opt(IDL.Float64),
    'buyerId' : UserId,
    'quantity' : IDL.Nat,
    'specialRequirements' : IDL.Text,
    'supplierId' : UserId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'supplier' : IDL.Null,
    'both' : IDL.Null,
    'buyer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'verified' : IDL.Bool,
    'supplierSize' : IDL.Opt(SupplierSize),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
    'email' : IDL.Text,
    'buyerTier' : IDL.Opt(BuyerTier),
  });
  const ProductStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'status' : ProductStatus,
    'specifications' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'certifications' : IDL.Text,
    'price' : IDL.Float64,
    'supplierId' : UserId,
  });
  const Result_2 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [Result_1],
        [],
      ),
    'calculateBuyerFee' : IDL.Func(
        [BuyerTier, IDL.Float64],
        [IDL.Float64],
        ['query'],
      ),
    'calculateMultiRoleFee' : IDL.Func(
        [BuyerTier, SupplierSize, IDL.Float64, IDL.Float64],
        [IDL.Float64],
        ['query'],
      ),
    'calculateSupplierFee' : IDL.Func(
        [SupplierSize, IDL.Float64],
        [IDL.Float64],
        ['query'],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [Result], []),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllRFQs' : IDL.Func([], [IDL.Vec(RFQ)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getIncomingRFQs' : IDL.Func([], [IDL.Vec(RFQ)], ['query']),
    'getMyProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyRFQs' : IDL.Func([], [IDL.Vec(RFQ)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'registerUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          UserRole,
          IDL.Opt(BuyerTier),
          IDL.Opt(SupplierSize),
        ],
        [Result_2],
        [],
      ),
    'respondToRFQ' : IDL.Func([IDL.Nat, IDL.Float64], [Result], []),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result_1], []),
    'submitRFQ' : IDL.Func(
        [IDL.Principal, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [Result_1],
        [],
      ),
    'updateFeedbackStatus' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Nat, IDL.Text],
        [Result],
        [],
      ),
    'updateRFQStatus' : IDL.Func([IDL.Nat, IDL.Text], [Result], []),
    'updateUserRole' : IDL.Func([IDL.Principal, UserRole], [Result], []),
    'verifyUser' : IDL.Func([IDL.Principal], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };