/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BuyerTier = { 'tier1' : null } |
  { 'tier2' : null } |
  { 'tier3' : null } |
  { 'tier4' : null };
export interface Feedback {
  'id' : bigint,
  'status' : FeedbackStatus,
  'userType' : string,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'message' : string,
  'rating' : bigint,
}
export type FeedbackStatus = { 'new' : null } |
  { 'closed' : null } |
  { 'reviewed' : null };
export interface Product {
  'id' : bigint,
  'status' : ProductStatus,
  'specifications' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : [] | [string],
  'category' : string,
  'certifications' : string,
  'price' : number,
  'supplierId' : UserId,
}
export type ProductStatus = { 'active' : null } |
  { 'inactive' : null };
export interface RFQ {
  'id' : bigint,
  'status' : RFQStatus,
  'createdAt' : Timestamp,
  'productId' : bigint,
  'requiredDate' : string,
  'quoteAmount' : [] | [number],
  'buyerId' : UserId,
  'quantity' : bigint,
  'specialRequirements' : string,
  'supplierId' : UserId,
}
export type RFQStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null } |
  { 'quoted' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_2 = { 'ok' : UserProfile } |
  { 'err' : string };
export type SupplierSize = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'verified' : boolean,
  'supplierSize' : [] | [SupplierSize],
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
  'email' : string,
  'buyerTier' : [] | [BuyerTier],
}
export type UserRole = { 'admin' : null } |
  { 'supplier' : null } |
  { 'both' : null } |
  { 'buyer' : null };
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [string, string, number, bigint, string, [] | [string], string, string],
    Result_1
  >,
  'calculateBuyerFee' : ActorMethod<[BuyerTier, number], number>,
  'calculateMultiRoleFee' : ActorMethod<
    [BuyerTier, SupplierSize, number, number],
    number
  >,
  'calculateSupplierFee' : ActorMethod<[SupplierSize, number], number>,
  'deleteProduct' : ActorMethod<[bigint], Result>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllRFQs' : ActorMethod<[], Array<RFQ>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getIncomingRFQs' : ActorMethod<[], Array<RFQ>>,
  'getMyProducts' : ActorMethod<[], Array<Product>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyRFQs' : ActorMethod<[], Array<RFQ>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'registerUser' : ActorMethod<
    [string, string, UserRole, [] | [BuyerTier], [] | [SupplierSize]],
    Result_2
  >,
  'respondToRFQ' : ActorMethod<[bigint, number], Result>,
  'submitFeedback' : ActorMethod<[string, bigint, string], Result_1>,
  'submitRFQ' : ActorMethod<
    [Principal, bigint, bigint, string, string],
    Result_1
  >,
  'updateFeedbackStatus' : ActorMethod<[bigint, string], Result>,
  'updateProduct' : ActorMethod<[bigint, number, bigint, string], Result>,
  'updateRFQStatus' : ActorMethod<[bigint, string], Result>,
  'updateUserRole' : ActorMethod<[Principal, UserRole], Result>,
  'verifyUser' : ActorMethod<[Principal], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];