/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type Result_2 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface Feedback {
    id: bigint;
    status: FeedbackStatus;
    userType: string;
    userId: UserId;
    createdAt: Timestamp;
    message: string;
    rating: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export type UserId = Principal;
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface RFQ {
    id: bigint;
    status: RFQStatus;
    createdAt: Timestamp;
    productId: bigint;
    requiredDate: string;
    quoteAmount?: number;
    buyerId: UserId;
    quantity: bigint;
    specialRequirements: string;
    supplierId: UserId;
}
export interface UserProfile {
    id: UserId;
    verified: boolean;
    supplierSize?: SupplierSize;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    buyerTier?: BuyerTier;
}
export interface Product {
    id: bigint;
    status: ProductStatus;
    specifications: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    stock: bigint;
    imageUrl?: string;
    category: string;
    certifications: string;
    price: number;
    supplierId: UserId;
}
export enum BuyerTier {
    tier1 = "tier1",
    tier2 = "tier2",
    tier3 = "tier3",
    tier4 = "tier4"
}
export enum FeedbackStatus {
    new_ = "new",
    closed = "closed",
    reviewed = "reviewed"
}
export enum ProductStatus {
    active = "active",
    inactive = "inactive"
}
export enum RFQStatus {
    pending = "pending",
    rejected = "rejected",
    accepted = "accepted",
    quoted = "quoted"
}
export enum SupplierSize {
    large = "large",
    small = "small",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    supplier = "supplier",
    both = "both",
    buyer = "buyer"
}
export interface backendInterface {
    addProduct(name: string, category: string, price: number, stock: bigint, description: string, imageUrl: string | null, specifications: string, certifications: string): Promise<Result_1>;
    calculateBuyerFee(tier: BuyerTier, amount: number): Promise<number>;
    calculateMultiRoleFee(buyerTier: BuyerTier, supplierSize: SupplierSize, buyerAmount: number, supplierSales: number): Promise<number>;
    calculateSupplierFee(size: SupplierSize, salesVolume: number): Promise<number>;
    deleteProduct(id: bigint): Promise<Result>;
    getAllFeedback(): Promise<Array<Feedback>>;
    getAllRFQs(): Promise<Array<RFQ>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getIncomingRFQs(): Promise<Array<RFQ>>;
    getMyProducts(): Promise<Array<Product>>;
    getMyProfile(): Promise<UserProfile | null>;
    getMyRFQs(): Promise<Array<RFQ>>;
    getProducts(): Promise<Array<Product>>;
    registerUser(name: string, email: string, role: UserRole, buyerTier: BuyerTier | null, supplierSize: SupplierSize | null): Promise<Result_2>;
    respondToRFQ(rfqId: bigint, quoteAmount: number): Promise<Result>;
    submitFeedback(userType: string, rating: bigint, message: string): Promise<Result_1>;
    submitRFQ(supplierId: Principal, productId: bigint, quantity: bigint, requiredDate: string, specialRequirements: string): Promise<Result_1>;
    updateFeedbackStatus(id: bigint, status: string): Promise<Result>;
    updateProduct(id: bigint, price: number, stock: bigint, status: string): Promise<Result>;
    updateRFQStatus(rfqId: bigint, status: string): Promise<Result>;
    updateUserRole(userId: Principal, role: UserRole): Promise<Result>;
    verifyUser(userId: Principal): Promise<Result>;
}
import type { BuyerTier as _BuyerTier, Feedback as _Feedback, FeedbackStatus as _FeedbackStatus, Product as _Product, ProductStatus as _ProductStatus, RFQ as _RFQ, RFQStatus as _RFQStatus, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, SupplierSize as _SupplierSize, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: string, arg1: string, arg2: number, arg3: bigint, arg4: string, arg5: string | null, arg6: string, arg7: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return from_candid_Result_1_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return from_candid_Result_1_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async calculateBuyerFee(arg0: BuyerTier, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateBuyerFee(to_candid_BuyerTier_n4(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateBuyerFee(to_candid_BuyerTier_n4(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async calculateMultiRoleFee(arg0: BuyerTier, arg1: SupplierSize, arg2: number, arg3: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateMultiRoleFee(to_candid_BuyerTier_n4(this._uploadFile, this._downloadFile, arg0), to_candid_SupplierSize_n6(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateMultiRoleFee(to_candid_BuyerTier_n4(this._uploadFile, this._downloadFile, arg0), to_candid_SupplierSize_n6(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async calculateSupplierFee(arg0: SupplierSize, arg1: number): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateSupplierFee(to_candid_SupplierSize_n6(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateSupplierFee(to_candid_SupplierSize_n6(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeedback(): Promise<Array<Feedback>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRFQs(): Promise<Array<RFQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRFQs();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRFQs();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomingRFQs(): Promise<Array<RFQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomingRFQs();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomingRFQs();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProducts();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProducts();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRFQs(): Promise<Array<RFQ>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRFQs();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRFQs();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: UserRole, arg3: BuyerTier | null, arg4: SupplierSize | null): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_UserRole_n39(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_2_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_UserRole_n39(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_2_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async respondToRFQ(arg0: bigint, arg1: number): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.respondToRFQ(arg0, arg1);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.respondToRFQ(arg0, arg1);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitFeedback(arg0: string, arg1: bigint, arg2: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1, arg2);
                return from_candid_Result_1_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1, arg2);
            return from_candid_Result_1_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitRFQ(arg0: Principal, arg1: bigint, arg2: bigint, arg3: string, arg4: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRFQ(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Result_1_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRFQ(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Result_1_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateFeedbackStatus(arg0: bigint, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFeedbackStatus(arg0, arg1);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFeedbackStatus(arg0, arg1);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: bigint, arg1: number, arg2: bigint, arg3: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRFQStatus(arg0: bigint, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRFQStatus(arg0, arg1);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRFQStatus(arg0, arg1);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: Principal, arg1: UserRole): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n39(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_UserRole_n39(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyUser(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUser(arg0);
                return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUser(arg0);
            return from_candid_Result_n8(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BuyerTier_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BuyerTier): BuyerTier {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_FeedbackStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeedbackStatus): FeedbackStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Feedback_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Feedback): Feedback {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ProductStatus_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductStatus): ProductStatus {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_RFQStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RFQStatus): RFQStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RFQ_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RFQ): RFQ {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_SupplierSize_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SupplierSize): SupplierSize {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierSize]): SupplierSize | null {
    return value.length === 0 ? null : from_candid_SupplierSize_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BuyerTier]): BuyerTier | null {
    return value.length === 0 ? null : from_candid_BuyerTier_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _FeedbackStatus;
    userType: string;
    userId: _UserId;
    createdAt: _Timestamp;
    message: string;
    rating: bigint;
}): {
    id: bigint;
    status: FeedbackStatus;
    userType: string;
    userId: UserId;
    createdAt: Timestamp;
    message: string;
    rating: bigint;
} {
    return {
        id: value.id,
        status: from_candid_FeedbackStatus_n13(_uploadFile, _downloadFile, value.status),
        userType: value.userType,
        userId: value.userId,
        createdAt: value.createdAt,
        message: value.message,
        rating: value.rating
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _RFQStatus;
    createdAt: _Timestamp;
    productId: bigint;
    requiredDate: string;
    quoteAmount: [] | [number];
    buyerId: _UserId;
    quantity: bigint;
    specialRequirements: string;
    supplierId: _UserId;
}): {
    id: bigint;
    status: RFQStatus;
    createdAt: Timestamp;
    productId: bigint;
    requiredDate: string;
    quoteAmount?: number;
    buyerId: UserId;
    quantity: bigint;
    specialRequirements: string;
    supplierId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_RFQStatus_n18(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        productId: value.productId,
        requiredDate: value.requiredDate,
        quoteAmount: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.quoteAmount)),
        buyerId: value.buyerId,
        quantity: value.quantity,
        specialRequirements: value.specialRequirements,
        supplierId: value.supplierId
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    verified: boolean;
    supplierSize: [] | [_SupplierSize];
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
    email: string;
    buyerTier: [] | [_BuyerTier];
}): {
    id: UserId;
    verified: boolean;
    supplierSize?: SupplierSize;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
    email: string;
    buyerTier?: BuyerTier;
} {
    return {
        id: value.id,
        verified: value.verified,
        supplierSize: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.supplierSize)),
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n27(_uploadFile, _downloadFile, value.role),
        email: value.email,
        buyerTier: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.buyerTier))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ProductStatus;
    specifications: string;
    name: string;
    createdAt: _Timestamp;
    description: string;
    stock: bigint;
    imageUrl: [] | [string];
    category: string;
    certifications: string;
    price: number;
    supplierId: _UserId;
}): {
    id: bigint;
    status: ProductStatus;
    specifications: string;
    name: string;
    createdAt: Timestamp;
    description: string;
    stock: bigint;
    imageUrl?: string;
    category: string;
    certifications: string;
    price: number;
    supplierId: UserId;
} {
    return {
        id: value.id,
        status: from_candid_ProductStatus_n35(_uploadFile, _downloadFile, value.status),
        specifications: value.specifications,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        stock: value.stock,
        imageUrl: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.imageUrl)),
        category: value.category,
        certifications: value.certifications,
        price: value.price,
        supplierId: value.supplierId
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    closed: null;
} | {
    reviewed: null;
}): FeedbackStatus {
    return "new" in value ? FeedbackStatus.new : "closed" in value ? FeedbackStatus.closed : "reviewed" in value ? FeedbackStatus.reviewed : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    accepted: null;
} | {
    quoted: null;
}): RFQStatus {
    return "pending" in value ? RFQStatus.pending : "rejected" in value ? RFQStatus.rejected : "accepted" in value ? RFQStatus.accepted : "quoted" in value ? RFQStatus.quoted : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    large: null;
} | {
    small: null;
} | {
    medium: null;
}): SupplierSize {
    return "large" in value ? SupplierSize.large : "small" in value ? SupplierSize.small : "medium" in value ? SupplierSize.medium : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    supplier: null;
} | {
    both: null;
} | {
    buyer: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "supplier" in value ? UserRole.supplier : "both" in value ? UserRole.both : "buyer" in value ? UserRole.buyer : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tier1: null;
} | {
    tier2: null;
} | {
    tier3: null;
} | {
    tier4: null;
}): BuyerTier {
    return "tier1" in value ? BuyerTier.tier1 : "tier2" in value ? BuyerTier.tier2 : "tier3" in value ? BuyerTier.tier3 : "tier4" in value ? BuyerTier.tier4 : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): ProductStatus {
    return "active" in value ? ProductStatus.active : "inactive" in value ? ProductStatus.inactive : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n22(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Feedback>): Array<Feedback> {
    return value.map((x)=>from_candid_Feedback_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RFQ>): Array<RFQ> {
    return value.map((x)=>from_candid_RFQ_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n33(_uploadFile, _downloadFile, x));
}
function to_candid_BuyerTier_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BuyerTier): _BuyerTier {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_SupplierSize_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierSize): _SupplierSize {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BuyerTier | null): [] | [_BuyerTier] {
    return value === null ? candid_none() : candid_some(to_candid_BuyerTier_n4(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierSize | null): [] | [_SupplierSize] {
    return value === null ? candid_none() : candid_some(to_candid_SupplierSize_n6(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    supplier: null;
} | {
    both: null;
} | {
    buyer: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.supplier ? {
        supplier: null
    } : value == UserRole.both ? {
        both: null
    } : value == UserRole.buyer ? {
        buyer: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BuyerTier): {
    tier1: null;
} | {
    tier2: null;
} | {
    tier3: null;
} | {
    tier4: null;
} {
    return value == BuyerTier.tier1 ? {
        tier1: null
    } : value == BuyerTier.tier2 ? {
        tier2: null
    } : value == BuyerTier.tier3 ? {
        tier3: null
    } : value == BuyerTier.tier4 ? {
        tier4: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SupplierSize): {
    large: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == SupplierSize.large ? {
        large: null
    } : value == SupplierSize.small ? {
        small: null
    } : value == SupplierSize.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
